// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUI_h
#define GUI_h
#include <FL/Fl.H>
#include "GUI_Spectre.hpp"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *debug_info_panel;
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
extern Fl_Button *btn_calculate;
extern Fl_Button *btn_4t;
#include <FL/Fl_Progress.H>
extern Fl_Progress *c4t_progress;
extern Fl_Button *btn_calibrate;
extern Fl_Progress *noise_generator_progress;
extern Fl_Button *csv_btn;
Fl_Double_Window* make_window();
extern unsigned char menu__i18n_done;
extern Fl_Menu_Item menu_[];
extern Fl_Double_Window *about_window;
#include <FL/Fl_Help_View.H>
Fl_Double_Window* make_about_window();
#include <FL/Fl_Slider.H>
extern Fl_Slider *dc_coef_slider;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *dc_coef_input;
Fl_Double_Window* make_dsp_window();
extern Fl_Double_Window *noise_mes_win;
extern GUI_Spectre *noise_spectre_box;
extern Fl_Button *start_noise_scan;
extern Fl_Button *stop_noise_scan;
extern Fl_Value_Input *noise_lower_input;
extern Fl_Value_Input *noise_upper_input;
Fl_Double_Window* make_measurement_window();
extern Fl_Double_Window *c4t_mes_win;
extern GUI_Spectre *c4t_spectre_box;
extern Fl_Button *start_c4t_scan;
extern Fl_Button *stop_c4t_scan;
extern Fl_Value_Input *c4t_lower_input;
extern Fl_Value_Input *c4t_upper_input;
Fl_Double_Window* make_4t_measurement_window();
extern Fl_Double_Window *corrected_window;
extern GUI_Spectre *corrected_spectre_box;
Fl_Double_Window* make_corrected_spectrum_window();
#endif
