// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef GUI_h
#define GUI_h
#include <FL/Fl.H>
#include "GUI_Spectre.hpp"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Value_Input.H>
#include <FL/Fl_Button.H>
extern Fl_Button *btn_calibrate;
extern GUI_Spectre *noise_spectre_box;
#include <FL/Fl_Menu_Bar.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *debug_info_panel;
Fl_Double_Window* make_window();
extern unsigned char menu__i18n_done;
extern Fl_Menu_Item menu_[];
Fl_Double_Window* make_about_window();
#endif
