// generated by Fast Light User Interface Designer (fluid) version 1.0305

#include <libintl.h>
#include "GUI.h"

static void cb_About(Fl_Menu_*, void*) {
  about_window = make_about_window();
about_window->show();
}

unsigned char menu__i18n_done = 0;
Fl_Menu_Item menu_[] = {
 {"File", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"DSP parameters", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {"About", 0,  (Fl_Callback*)cb_About, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 10, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Text_Display *debug_info_panel=(Fl_Text_Display *)0;

Fl_Button *btn_calibrate=(Fl_Button *)0;

Fl_Progress *noise_generator_progress=(Fl_Progress *)0;

Fl_Double_Window* make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(695, 375, gettext("nbima"));
    w = o; if (w) {/* empty */}
    o->color((Fl_Color)55);
    o->labelsize(12);
    o->when(FL_WHEN_RELEASE_ALWAYS);
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 1150, 25);
      o->box(FL_FLAT_BOX);
      o->color((Fl_Color)53);
      if (!menu__i18n_done) {
        int i=0;
        for ( ; i<3; i++)
          if (menu_[i].label())
            menu_[i].label(gettext(menu_[i].label()));
        menu__i18n_done = 1;
      }
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { debug_info_panel = new Fl_Text_Display(15, 290, 665, 70, gettext("Debug info"));
      debug_info_panel->box(FL_GTK_THIN_DOWN_FRAME);
      debug_info_panel->labelsize(11);
      debug_info_panel->textfont(4);
      debug_info_panel->textsize(11);
      debug_info_panel->align(Fl_Align(FL_ALIGN_TOP_LEFT));
    } // Fl_Text_Display* debug_info_panel
    { Fl_Group* o = new Fl_Group(160, 60, 155, 145);
      o->box(FL_BORDER_FRAME);
      o->color(FL_FOREGROUND_COLOR);
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(420, 65, 90, 65);
      o->box(FL_BORDER_FRAME);
      o->color(FL_FOREGROUND_COLOR);
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(485, 45, 195, 105, gettext("RTL-SDR"));
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)55);
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(195, 129, 85, 91);
      o->box(FL_BORDER_FRAME);
      o->color(FL_FOREGROUND_COLOR);
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(140, 165, 195, 105, gettext("Corrected Spectrum"));
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)55);
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      { Fl_Button* o = new Fl_Button(150, 235, 175, 25, gettext("Calculate"));
        o->box(FL_GTK_UP_BOX);
        o->color((Fl_Color)55);
        o->labelsize(11);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(260, 45, 195, 105, gettext("Antenna"));
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)55);
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      { Fl_Button* o = new Fl_Button(270, 115, 175, 25, gettext("Measure"));
        o->box(FL_GTK_UP_BOX);
        o->color((Fl_Color)55);
        o->labelsize(11);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(20, 45, 195, 105, gettext("Noise generator"));
      o->box(FL_BORDER_BOX);
      o->color((Fl_Color)55);
      o->labelsize(12);
      o->align(Fl_Align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE));
      { btn_calibrate = new Fl_Button(30, 115, 175, 25, gettext("Measure"));
        btn_calibrate->box(FL_GTK_UP_BOX);
        btn_calibrate->color((Fl_Color)55);
        btn_calibrate->labelsize(11);
      } // Fl_Button* btn_calibrate
      { Fl_Progress* o = noise_generator_progress = new Fl_Progress(30, 54, 175, 17, gettext("Progress..."));
        noise_generator_progress->box(FL_GTK_DOWN_BOX);
        noise_generator_progress->selection_color((Fl_Color)180);
        noise_generator_progress->labelsize(11);
        noise_generator_progress->hide();
        o->value(32);
      } // Fl_Progress* noise_generator_progress
      o->end();
    } // Fl_Group* o
    { Fl_Button* o = new Fl_Button(250, 175, 75, 20, gettext("save to .csv"));
      o->box(FL_GTK_UP_BOX);
      o->color((Fl_Color)55);
      o->labelsize(10);
      o->labelcolor(FL_SELECTION_COLOR);
    } // Fl_Button* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}

Fl_Double_Window *about_window=(Fl_Double_Window *)0;

Fl_Double_Window* make_about_window() {
  { about_window = new Fl_Double_Window(270, 260);
    about_window->color((Fl_Color)55);
    { Fl_Help_View* o = new Fl_Help_View(0, 0, 270, 260, gettext("About"));
      o->box(FL_FLAT_BOX);
      o->load("../about.html");
    } // Fl_Help_View* o
    about_window->size_range(0, 0, 270, 260);
    about_window->end();
  } // Fl_Double_Window* about_window
  return about_window;
}

Fl_Slider *dc_coef_slider=(Fl_Slider *)0;

static void cb_dc_coef_slider(Fl_Slider* o, void*) {
  dc_coef_input->value(o->value());
}

Fl_Value_Input *dc_coef_input=(Fl_Value_Input *)0;

static void cb_dc_coef_input(Fl_Value_Input* o, void*) {
  dc_coef_slider->value(o->value());
}

Fl_Double_Window* make_dsp_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(330, 65, gettext("DSP parameters"));
    w = o; if (w) {/* empty */}
    o->hotspot(o);
    { dc_coef_slider = new Fl_Slider(150, 35, 170, 20);
      dc_coef_slider->type(1);
      dc_coef_slider->labelsize(12);
      dc_coef_slider->value(1);
      dc_coef_slider->callback((Fl_Callback*)cb_dc_coef_slider);
      dc_coef_slider->align(Fl_Align(FL_ALIGN_LEFT_TOP));
    } // Fl_Slider* dc_coef_slider
    { dc_coef_input = new Fl_Value_Input(150, 10, 170, 20, gettext("DC blocker coefficient"));
      dc_coef_input->labelsize(12);
      dc_coef_input->value(1);
      dc_coef_input->textsize(12);
      dc_coef_input->callback((Fl_Callback*)cb_dc_coef_input);
    } // Fl_Value_Input* dc_coef_input
    o->end();
  } // Fl_Double_Window* o
  return w;
}

GUI_Spectre *noise_spectre_box=(GUI_Spectre *)0;

Fl_Button *start_noise_scan=(Fl_Button *)0;

Fl_Double_Window* make_measurement_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(800, 175, gettext("Noise generator"));
    w = o; if (w) {/* empty */}
    o->color((Fl_Color)38);
    { Fl_Group* o = new Fl_Group(0, 35, 800, 150);
      { noise_spectre_box = new GUI_Spectre(0, 35, 800, 140, gettext("Estimated noise spectrum"));
        noise_spectre_box->box(FL_FLAT_BOX);
        noise_spectre_box->color(FL_FOREGROUND_COLOR);
        noise_spectre_box->selection_color(FL_BACKGROUND_COLOR);
        noise_spectre_box->labeltype(FL_NO_LABEL);
        noise_spectre_box->labelfont(0);
        noise_spectre_box->labelsize(11);
        noise_spectre_box->labelcolor(FL_FOREGROUND_COLOR);
        noise_spectre_box->align(Fl_Align(FL_ALIGN_TOP));
        noise_spectre_box->when(FL_WHEN_RELEASE);
        Fl_Group::current()->resizable(noise_spectre_box);
      } // GUI_Spectre* noise_spectre_box
      o->end();
      Fl_Group::current()->resizable(o);
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(0, 0, 800, 35);
      { Fl_Group* o = new Fl_Group(5, 0, 285, 35);
        { start_noise_scan = new Fl_Button(5, 5, 25, 25, gettext(">"));
          start_noise_scan->type(1);
          start_noise_scan->box(FL_GTK_UP_BOX);
          start_noise_scan->down_box(FL_GTK_DOWN_BOX);
          start_noise_scan->color((Fl_Color)106);
          start_noise_scan->selection_color((Fl_Color)106);
          start_noise_scan->labelfont(1);
          start_noise_scan->labelcolor((Fl_Color)62);
        } // Fl_Button* start_noise_scan
        { Fl_Button* o = new Fl_Button(35, 5, 25, 25, gettext("||"));
          o->box(FL_GTK_UP_BOX);
          o->down_box(FL_GTK_DOWN_BOX);
          o->color(FL_DARK3);
          o->selection_color((Fl_Color)36);
          o->labelfont(5);
          o->labelsize(10);
          o->labelcolor((Fl_Color)80);
        } // Fl_Button* o
        { Fl_Value_Input* o = new Fl_Value_Input(145, 5, 45, 25, gettext("MHz -"));
          o->box(FL_GTK_DOWN_BOX);
          o->color((Fl_Color)40);
          o->labelsize(12);
          o->labelcolor((Fl_Color)51);
          o->value(30);
          o->textsize(12);
          o->textcolor((Fl_Color)51);
          o->align(Fl_Align(FL_ALIGN_RIGHT));
        } // Fl_Value_Input* o
        { Fl_Button* o = new Fl_Button(65, 5, 75, 25, gettext("save to .csv"));
          o->box(FL_GTK_UP_BOX);
          o->down_box(FL_GTK_DOWN_BOX);
          o->color(FL_DARK3);
          o->selection_color((Fl_Color)36);
          o->labelsize(10);
          o->labelcolor((Fl_Color)51);
        } // Fl_Button* o
        { Fl_Value_Input* o = new Fl_Value_Input(230, 5, 45, 25, gettext("MHz"));
          o->box(FL_GTK_DOWN_BOX);
          o->color((Fl_Color)40);
          o->labelsize(12);
          o->labelcolor((Fl_Color)51);
          o->value(1030);
          o->textsize(12);
          o->textcolor((Fl_Color)51);
          o->align(Fl_Align(FL_ALIGN_RIGHT));
        } // Fl_Value_Input* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(310, 5, 490, 25);
        o->end();
        Fl_Group::current()->resizable(o);
      } // Fl_Group* o
      o->end();
    } // Fl_Group* o
    o->end();
  } // Fl_Double_Window* o
  return w;
}
